# Generated by Django 4.0.6 on 2022-11-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.DeleteModel(
            name='StudyDate',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
